platform :ios, '7.0'
workspace 'ShiftScheduler.xcworkspace'
pod 'REFrostedViewController', '~> 2.4'
#pod 'EAIntroView', '~> 1.3.2'
pod 'WSCoachMarksView', '~> 0.2'
pod 'KKColorListPicker', '~>0.2.4'
pod 'WeixinActivity',:git => 'https://github.com/kzjeef/WeixinActivity.git', :commit => '5ed53ea'
